### PR TITLE
Create a proper plugin

### PR DESCRIPTION
**Pull request by EinRainerZufall**
I had a problem with the spaces in `uuid.gd` so I changed all spaces to tabs,
I have created the `config.cfg` with the necessary metadata.

And then I created a small tool script that loads the `uuid.gd` as a global script when the plugin is activated and unloads it again when the plugin is deactivated.

And finally, I modified the `.gitattributes` so that only the addon folder is added during import.

ps.: and please add the new version to the Godot asset library. The latest version in the library is 2.1.1

### CODE REVIEW

**Comment by EinRainerZufall** [comment]
As additional information:
To follow the Godot naming convention, you would have to change the folder structure to “addons/godot-uuid”. However, I didn't want to make this change because I don't know what this means for backward compatibility.

https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html

**Comment by xsellier** [comment]
Hey,

Thakn you for the PR, however I'm not gonna switch from spaces to tabs.

**Comment by EinRainerZufall** [comment]
Ok and without this change? Would the rest be okay?

**Comment by xsellier** [comment]
I have my own convention not looking any new one. thanks for asking.

**Comment by xsellier** [comment]
Without it, I'm gonna have to test it, double check it on my own, then Im gonna merge it if everything works great  and eventually publish it on the asset store.

**Comment by EinRainerZufall** [comment]
ok I have reversed the changes in `uuid.gd`.

**Comment by EinRainerZufall** [comment]
Out of interest I would like to know why spaces are used? And whether you also use the built-in editor of Godot or an external one?

**Comment by xsellier** [comment]
I do use an external one. Spaces are easier to handle than tabs. Let's say you put a space in a tab indented file, you won't see it in your editor right away. However if you put a tab in a space indented file, then you spot it right away since you can replace tabs by spaces using a macro.

**Comment by xsellier** [comment]
Thank you for helping.
So I've tested it, and updated the test.gd file, replaced all remaining tabs by spaces and `"` by `'`.
The asset has been updated on the godot asset store.

Happy holidays !

**Comment by EinRainerZufall** [comment]
I have one more question: Why did you delete the static typing in `uuid.gd`? GDScript should run a bit faster if it is statically typed.

**Comment by xsellier** [comment]
I did some bench, without it it's somewhat 1% faster. So I removed it

**Pull request merged**
